#!/usr/bin/zsh

BYPASS=false

while getopts "b" options; do
	case $options in
		c)
			BYPASS=true
		;;
	esac
done

cheat_dir=$(dirname "$(readlink -f "$0")")/cheat_md/

#If there is args 
if [[ $# -eq 1  ]]; then 
	#if Cheat exists :
    if [[ -f $cheat_dir/"$1".md && !$BYPASS ]]; then
        mdv $cheat_dir/"$1".md
    else
	#If not, lets curl in cheat.sh
    	curl cheat.sh/$1
	fi
	echo $BYPASS	
else
    echo "# Here is the cheats available :" |  mdv -
    ls -c $cheat_dir/ | sed 's/\.md//g'
fi    
echo "-------------"

