#!/usr/bin/zsh

BYPASS=0
cheat_dir=$(dirname "$(readlink -f "$0")")/cheat_md/

bold=$(tput bold)
normal=$(tput sgr0)
red=$(tput setaf 1)


#Parse options :
OPTS=$( getopt -o b -l bypass -- "$@" )
if [ $? != 0 ]; then exit 1; fi
eval set -- "$OPTS"
while true ; do
	case "$1" in
		-b | --bypass)
			BYPASS=1
			shift 1 ;;
		--)
			shift;
			break;;
	esac
done

subject=$1

if [[ $# -eq 0 ]]; then

    echo "# Here is the cheats available :" |  mdv -
    ls -c $cheat_dir/ | sed 's/\.md//g'

else

	#if Cheat exists and bypass is unwanted :
	if [[ -f $cheat_dir/"$subject".md && $BYPASS -eq 0 ]] ; then
	    mdv $cheat_dir/"$subject".md
	else
	#If not, lets curl in cheat.sh
		curl cheat.sh/$subject
	fi

fi

echo -e "\n ${bold}Tip :${normal} You can also get cheat sheet on cheat.sh by bypassing markdown with ${bold} -b ${normal} or ${bold}--bypass ${normal} option \n"

